name: Publish feed generators

on:
  workflow_dispatch:

env:
  BLUESKY_HANDLE: ${{ vars.BLUESKY_HANDLE }}
  BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_WORKER_NAME: ${{ vars.CLOUDFLARE_WORKER_NAME }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  publish_feed_generators:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Get Cloudflare Worker URL
        run: |
          set -o pipefail;
          tmp=$(mktemp);
          curl -f \
              --request GET \
              --url "https://api.cloudflare.com/client/v4/accounts/${{ env.CLOUDFLARE_ACCOUNT_ID }}/workers/subdomain" \
              --header 'Content-Type: application/json' \
              --header 'Authorization: Bearer ${{ env.CLOUDFLARE_API_TOKEN }}' \
              | jq -r '.result.subdomain' > $tmp
          export CLOUDFLARE_WORKERS_SUBDOMAIN="$(cat $tmp)"
          echo "CLOUDFLARE_WORKER_URL=${CLOUDFLARE_WORKER_NAME}.${CLOUDFLARE_WORKERS_SUBDOMAIN}.workers.dev" >> "$GITHUB_ENV"

      - name: Install
        run: npm install

      - name: Run script
        run: npm run publishFeed
